services:

  nats-server:
    image: nats:latest
    
  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/client-gateway
    # image: client-gateway-prod
    ports:
      - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
    environment:
      - PORT=${CLIENT_GATEWAY_PORT}
      - NATS_SERVERS=nats://nats-server:4222


  auth-ms:
    build:
      context: ./auth-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/auth-ms
    # image: auth-ms-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  products-ms:
    build:
      context: ./products-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/products-ms
    # image: products-ms-prod
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db

  
  # Orders MS
  orders-ms:
    build: 
      context: ./orders-ms
      dockerfile: dockerfile.prod
      args:
        - ORDERS_DATABASE_URL=${ORDERS_DATABASE_URL}
    image: northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/orders-ms
    # image: orders-ms-prod
    environment:
      - PORT=3000
      - DATABASE_URL=${ORDERS_DATABASE_URL}
      - NATS_SERVERS=nats://nats-server:4222


# ======================
# Payments Microservice
# ======================
  payments-ms:
    build:
      context: ./payments-ms
      dockerfile: dockerfile.prod
    image: northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/payments-ms
    # image: payments-ms
    ports:
      - ${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}