apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
      - image: northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/payments-ms
        name: payments-ms
        env:
        - name: PORT
          value: "8080"
        - name: NATS_SERVERS
          value: "nats://nats"
        - name: STRIPE_SUCCESS_URL
          value: "http://payments-ms:8080/webhook/stripe/success"
        - name: STRIPE_CANCEL_URL
          value: "http://payments-ms:8080/webhook/stripe/success"
        - name: STRIPE_ENDPOINT_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_endpoint_secret
        - name: STRIPE_SECRET
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: payments-secrets
              key: stripe_secret_key
status: {}
