apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      labels:
        app: client-gateway
    spec:
      containers:
        - name: client-gateway
          image: northamerica-south1-docker.pkg.dev/orders-portal-447714/nestjs-course/image-registry/client-gateway
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats"
          resources: {}  # <-- aquí debe ir